export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
//
export const GET_CATEGORIES = "GET_CATEGORIES";
// 
export const GET_USERS = "GET_USERS"  ; 
export const SET_USERS = "SET_USERS"  ; 
export const GET_USERS_ACCEPTED = "GET_USERS_ACCEPTED";
export const GET_USERS_BANNED = "GET_USERS_BANNED";
export const GET_USERS_QEUEU = "GET_USERS_QEUEU";
export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const DESACTIVE_ACCOUNT = "DESACTIVE_ACCOUNT";
export const BANNE_ACCOUNT = "BANNE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UN_BANNE_ACCOUNT = "UN_BANNE_ACCOUNT";
export const SEARCH_USER = "SEARCH_USER";
export const UPDATE_USER = "UPDATE_USER";
//
export const GET_PRODUCTS = "GET_PRODUCTS"  ; 
export const SET_PRODUCT = "SET_PRODUCT"  ; 
export const SET_PRODUCTS = "SET_PRODUCTS"  ; 
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT"  ; 
export const SET_PRODUCTS_BY_CATEGORY = "SET_PRODUCTS_BY_CATEGORY"  ; 
export const DELETE_PRODUCT = "DELETE_PRODUCT"  ; 
export const ACCEPTE_PRODUCT = "ACCEPTE_PRODUCT"  ; 
export const PRODUCT_ADDED_SUCCESFULY = "PRODUCT_ADDED_SUCCESFULY"  ; 
//
export const SET_ALL_MUSICS = "SET_ALL_MUSICS"  ; 
export const SET_MY_OWN_MUSICS = "SET_MY_OWN_MUSICS"  ; 
export const MY_MUSIC_QUEUE = "MY_MUSIC_QUEUE"  ; 
export const MY_MUSIC_POSTED = "MY_MUSIC_POSTED"  ; 
export const SET_MUSIC_LIKED = "SET_MUSIC_LIKED";
export const UN_LIKE_MUSIC = "UN_LIKE_MUSIC";
export const ACCEPTE_MUSIC = "ACCEPTE_MUSIC";
export const DELETE_MUSIC = "DELETE_MUSIC";
export const ADD_NEW_MUSIC = "ADD_NEW_MUSIC";
export const UPDATE_MUSIC_POSTED = "UPDATE_MUSIC_POSTED";
export const UPDATE_MUSIC_QEUEU = "UPDATE_MUSIC_QEUEU";
//
export const SET_MY_OWN_PRODUCT = "MY_OWN_PRODUCTS";
export const MY_PRODUCT_QUEUE = "MY_PRODUCT_QUEUE";
export const MY_PRODUCT_ACCEPTED = "MY_PRODUCT_ACCEPTED";
export const SET_PRODUCT_LIKED = "SET_PRODUCT_LIKED";
export const UN_LIKE_PRODUCT = "UN_LIKE_PRODUCT";
export const SET_ALL_PRODUCTS_IN_DB="SET_ALL_PRODUCTS_IN_DB";
//

export const SET_ALL_SIZES="SET_ALL_SIZES";

//
export const SET_PUBLIC_PRODUCTS = "SET_PUBLIC_PRODUCTS";
export const SET_PUBLIC_PRODUCT = "SET_PUBLIC_PRODUCT";
export const SET_PRODUCTS_SAME_SELLER = "SET_PRODUCTS_SAME_SELLER";
export const SET_PRODUCTS_SAME_CATEGORY = "SET_PRODUCTS_SAME_CATEGORY";
export const SET_PRODUCTS_WITH_CATEGORYID = "SET_PRODUCT_WITH_CATEGORYID";
export const REMOVE_SELECTED_PUBLIC_PRODUCT = "REMOVE_SELECTED_PUBLIC_PRODUCT";
export const GET_PRODUCT_OF_CATEGORY="GET_PRODUCT_OF_CATEGORY";
export const SET_PUBLIC_MUSICS = "SET_PUBLIC_MUSICS";
export const SET_PUBLIC_MUSIC = "SET_PUBLIC_MUSIC";
export const UNSET_PUBLIC_MUSIC = "UNSET_PUBLIC_MUSIC";
export const SET_MUSICS_OF_CURRENT_PUBLIC_ARTIST = "SET_MUSICS_OF_CURRENT_PUBLIC_ARTIST";
export const SET_CURRENT_PUBLIC_ARTIST = "SET_CURRENT_PUBLIC_ARTIST";
export const UNSET_CURRENT_PUBLIC_ARTIST = "UNSET_CURRENT_PUBLIC_ARTIST";
export const SET_FRIENDS_CURRENT_PUBLIC_ARTIST = "SET_FRIENDS_CURRENT_PUBLIC_ARTIST";

export const UNSET_MUSICS_OF_CURRENT_PUBLIC_ARTIST = "UNSET_MUSICS_OF_CURRENT_PUBLIC_ARTIST";
export const UNSET_FRIENDS_CURRENT_PUBLIC_ARTIST = "UNSET_FRIENDS_CURRENT_PUBLIC_ARTIST";
export const SET_ARTISTS_FOLLOWER_BY_USER_AUTHENTICATED="SET_ARTISTS_FOLLOWER_BY_USER_AUTHENTICATED";
export const UNFOLLOW_ARTIST ="UNFOLLOW_ARTIST ";
export const FOLLOW_ARTIST ="FOLLOW_ARTIST ";
export const FOLLOW_SIMPLE_ARTIST ="FOLLOW_SIMPLE_ARTIST ";
export const LIKE_MUSIC_BY_AUTHENTICATED ="LIKE_MUSIC_BY_AUTHENTICATED";
export const UN_LIKE_MUSIC_BY_AUTHENTICATED ="UN_LIKE_MUSIC_BY_AUTHENTICATED ";
export const SET_MUSIC_LIKED_BY_AUTHENTICATED = "SET_MUSIC_LIKED_BY_AUTHENTICATED";
export const SET_MUSICS_OF_USERS_WICH_IM_FOLLOWING = "SET_MUSICS_OF_USERS_WICH_IM_FOLLOWING";
export const SET_UNFOLLOW_ARTIST_OF_CURRENT_USER = "SET_UNFOLLOW_ARTIST_OF_CURRENT_USER";
export const SET_PRODUCTS_OF_USERS_WICH_IM_FOLLOWING = "SET_PRODUCTS_OF_USERS_WICH_IM_FOLLOWING";